// Seed data for populating Firestore with initial fictional data
// This file is only used by seed-firestore.ts and the seed button in Settings

import type {
  Empresa,
  Departamento,
  Pessoa,
  Ramal,
  Aviso,
  ListaNegraEntry,
  AchadosPerdidosItem,
  RegistroFluxo,
  RegistroVeiculo,
  PreAutorizacao,
  ProtocoloEmergencia,
  AtivacaoProtocolo,
  Ocorrencia,
  Ronda,
  ChecklistTurno,
  InspecaoDiaria,
} from './data';
import {
  ITENS_CHECKLIST_PADRAO,
  ITENS_INSPECAO_PADRAO,
} from './data';

// Pre-populated fictional data
export const EMPRESAS_INICIAIS: Empresa[] = [
  { id: 'emp1', nome: 'Transportes Silva Ltda', cnpj: '12.345.678/0001-90', contato: '(11) 98765-4321' },
  { id: 'emp2', nome: 'Logística Rápida S.A.', cnpj: '23.456.789/0001-01', contato: '(11) 91234-5678' },
  { id: 'emp3', nome: 'Distribuidora Central', cnpj: '34.567.890/0001-12', contato: '(11) 92345-6789' },
  { id: 'emp4', nome: 'Serviços Gerais Premium', cnpj: '45.678.901/0001-23', contato: '(11) 93456-7890' },
  { id: 'emp5', nome: 'Coleta Verde Ambiental', cnpj: '56.789.012/0001-34', contato: '(11) 94567-8901' },
  { id: 'emp6', nome: 'Manutenção Total EIRELI', cnpj: '67.890.123/0001-45', contato: '(11) 95678-9012' },
];

export const DEPARTAMENTOS_INICIAIS: Departamento[] = [
  { id: 'dep1', nome: 'Recepção', responsavel: 'Ana Costa' },
  { id: 'dep2', nome: 'Segurança', responsavel: 'Carlos Silva' },
  { id: 'dep3', nome: 'RH', responsavel: 'Maria Santos' },
  { id: 'dep4', nome: 'Financeiro', responsavel: 'Pedro Oliveira' },
  { id: 'dep5', nome: 'Logística', responsavel: 'João Pereira' },
  { id: 'dep6', nome: 'Almoxarifado', responsavel: 'Lucia Ferreira' },
  { id: 'dep7', nome: 'TI', responsavel: 'Roberto Lima' },
  { id: 'dep8', nome: 'Diretoria', responsavel: 'Fernando Souza' },
];

export const PESSOAS_INICIAIS: Pessoa[] = [
  { id: 'func1', nome: 'Carlos Eduardo Silva', tipo: 'Colaborador', empresa: '', departamento: 'Segurança', cargo: 'Porteiro', rgCpf: '12.345.678-9', placa: '', telefone: '(11) 99876-5432', email: 'carlos.silva@apex.com', dataCadastro: '2025-01-10' },
  { id: 'func2', nome: 'Ana Maria Costa', tipo: 'Colaborador', empresa: '', departamento: 'Recepção', cargo: 'Recepcionista', rgCpf: '23.456.789-0', placa: '', telefone: '(11) 98765-4321', email: 'ana.costa@apex.com', dataCadastro: '2025-01-10' },
  { id: 'func3', nome: 'João Pedro Oliveira', tipo: 'Colaborador', empresa: '', departamento: 'Segurança', cargo: 'Supervisor', rgCpf: '34.567.890-1', placa: '', telefone: '(11) 97654-3210', email: 'joao.oliveira@apex.com', dataCadastro: '2025-01-10' },
  { id: 'func4', nome: 'Maria Fernanda Santos', tipo: 'Colaborador', empresa: '', departamento: 'RH', cargo: 'Analista RH', rgCpf: '45.678.901-2', placa: '', telefone: '(11) 96543-2109', email: 'maria.santos@apex.com', dataCadastro: '2025-01-10' },
  { id: 'func5', nome: 'Roberto Junior Lima', tipo: 'Colaborador', empresa: '', departamento: 'TI', cargo: 'Técnico TI', rgCpf: '56.789.012-3', placa: '', telefone: '(11) 95432-1098', email: 'roberto.lima@apex.com', dataCadastro: '2025-01-10' },
  { id: 'func6', nome: 'Fernando Souza', tipo: 'Colaborador', empresa: '', departamento: 'Diretoria', cargo: 'Diretor', rgCpf: '456.789.012-33', placa: 'XYZ-5L67', telefone: '(11) 94321-0987', email: 'fernando.souza@apex.com', dataCadastro: '2025-01-10' },
  { id: 'pes1', nome: 'José da Silva', tipo: 'Motorista', empresa: 'Transportes Silva Ltda', departamento: '', cargo: 'Motorista', rgCpf: '12.345.678-9', placa: 'ABC-1D23', telefone: '(11) 91234-5678', email: '', dataCadastro: '2025-01-10' },
  { id: 'pes2', nome: 'Pedro Henrique Santos', tipo: 'Entregador', empresa: 'Distribuidora Central', departamento: '', cargo: 'Entregador', rgCpf: '23.456.789-0', placa: '', telefone: '(11) 92345-6789', email: '', dataCadastro: '2025-01-10' },
  { id: 'pes3', nome: 'Dr. Paulo Renato', tipo: 'Visitante', empresa: 'Advocacia Renato & Filhos', departamento: 'Diretoria', cargo: 'Advogado', rgCpf: '987.654.321-00', placa: 'MNO-3H45', telefone: '(11) 93456-7890', email: 'paulo@renatoadv.com', dataCadastro: '2025-01-10' },
  { id: 'pes4', nome: 'Eletricista João Batista', tipo: 'Prestador', empresa: 'JB Elétrica', departamento: 'TI', cargo: 'Eletricista', rgCpf: '321.098.765-66', placa: '', telefone: '(11) 94567-8901', email: '', dataCadastro: '2025-01-10' },
  { id: 'pes5', nome: 'Walter Nascimento', tipo: 'Motorista', empresa: 'Coleta Verde Ambiental', departamento: '', cargo: 'Motorista', rgCpf: '66.777.888-9', placa: 'PQR-6I78', telefone: '(11) 95678-9012', email: '', dataCadastro: '2025-01-10' },
  { id: 'pes6', nome: 'Pedro Marcelino', tipo: 'Prestador', empresa: 'Manutenção Total EIRELI', departamento: 'Almoxarifado', cargo: 'Técnico de Manutenção', rgCpf: '210.987.654-77', placa: '', telefone: '(11) 96789-0123', email: '', dataCadastro: '2025-01-10' },
  { id: 'pes7', nome: 'Luciana Moraes', tipo: 'Visitante', empresa: 'Consultora Empresarial', departamento: 'RH', cargo: 'Consultora', rgCpf: '876.543.210-11', placa: '', telefone: '(11) 97890-1234', email: 'luciana@moraes.com', dataCadastro: '2025-01-10' },
  { id: 'pes8', nome: 'Augusto Pinto', tipo: 'Motorista', empresa: 'Coleta Verde Ambiental', departamento: '', cargo: 'Motorista', rgCpf: '77.888.999-0', placa: 'STU-9J01', telefone: '(11) 98901-2345', email: '', dataCadastro: '2025-01-10' },
];

export const RAMAIS_INICIAIS: Ramal[] = [
  { id: 'ram1', departamento: 'Recepção', nome: 'Ana Costa', ramal: '100' },
  { id: 'ram2', departamento: 'Segurança', nome: 'Carlos Silva', ramal: '101' },
  { id: 'ram3', departamento: 'Segurança', nome: 'Portaria', ramal: '102' },
  { id: 'ram4', departamento: 'RH', nome: 'Maria Santos', ramal: '200' },
  { id: 'ram5', departamento: 'Financeiro', nome: 'Pedro Oliveira', ramal: '201' },
  { id: 'ram6', departamento: 'Financeiro', nome: 'Contas a Pagar', ramal: '202' },
  { id: 'ram7', departamento: 'Logística', nome: 'João Pereira', ramal: '300' },
  { id: 'ram8', departamento: 'Logística', nome: 'Expedição', ramal: '301' },
  { id: 'ram9', departamento: 'Almoxarifado', nome: 'Lucia Ferreira', ramal: '400' },
  { id: 'ram10', departamento: 'TI', nome: 'Roberto Lima', ramal: '500' },
  { id: 'ram11', departamento: 'TI', nome: 'Suporte', ramal: '501' },
  { id: 'ram12', departamento: 'Diretoria', nome: 'Fernando Souza', ramal: '600' },
  { id: 'ram13', departamento: 'Diretoria', nome: 'Secretaria', ramal: '601' },
  { id: 'ram14', departamento: 'Comercial', nome: 'Vendas', ramal: '700' },
  { id: 'ram15', departamento: 'Compras', nome: 'Suprimentos', ramal: '800' },
];

export const AVISOS_INICIAIS: Aviso[] = [
  {
    id: 'av1',
    titulo: 'Manutenção do Sistema de CFTV',
    conteudo: 'O sistema de câmeras passará por manutenção preventiva no dia 20/03/2025, das 22h às 06h. Favor redobrar a atenção na vigilância durante este período.',
    prioridade: 'alta',
    data: '2025-03-15',
    autor: 'Roberto Lima',
    turno: 'noturno',
    categoria: 'Segurança',
    dataExpiracao: '2025-03-21',
    fixado: true,
    lidoPor: ['Carlos Eduardo Silva'],
  },
  {
    id: 'av2',
    titulo: 'Novo Procedimento de Entrada',
    conteudo: 'A partir de 01/04/2025, todos os visitantes deverão apresentar documento com foto e realizar cadastro prévio pelo sistema. Procedure antigo será descontinuado.',
    prioridade: 'media',
    data: '2025-03-12',
    autor: 'Carlos Silva',
    turno: 'todos',
    categoria: 'Operacional',
    dataExpiracao: '2025-04-01',
    fixado: false,
    lidoPor: [],
  },
  {
    id: 'av3',
    titulo: 'Treinamento de Segurança',
    conteudo: 'Será realizado treinamento de segurança patrimonial no dia 25/03/2025 às 14h na sala de reuniões. Presença obrigatória para toda a equipe de portaria.',
    prioridade: 'media',
    data: '2025-03-10',
    autor: 'João Pedro Oliveira',
    turno: 'diurno',
    categoria: 'Administrativo',
    dataExpiracao: '2025-03-25',
    fixado: false,
    lidoPor: ['Carlos Eduardo Silva', 'Ana Maria Costa'],
  },
  {
    id: 'av4',
    titulo: 'Alteração de Horário de Almoço',
    conteudo: 'Informamos que o horário de almoço da equipe de portaria foi alterado para o período de 12h às 13h, com escala rotativa. Favor consultar o novo quadro de horários.',
    prioridade: 'baixa',
    data: '2025-03-08',
    autor: 'Maria Fernanda Santos',
    turno: 'todos',
    categoria: 'Administrativo',
    dataExpiracao: '',
    fixado: false,
    lidoPor: [],
  },
  {
    id: 'av5',
    titulo: 'Vaga de Estacionamento',
    conteudo: 'As vagas de estacionamento visitantes 01 a 05 estão interditadas para pintura e sinalização até o dia 22/03/2025. Direcionar visitantes para vagas 06 a 15.',
    prioridade: 'alta',
    data: '2025-03-14',
    autor: 'Carlos Silva',
    turno: 'todos',
    categoria: 'Operacional',
    dataExpiracao: '2025-03-22',
    fixado: true,
    lidoPor: ['Carlos Eduardo Silva'],
  },
];

export const LISTA_NEGRA_INICIAL: ListaNegraEntry[] = [
  {
    id: 'ln1',
    nome: 'Ricardo Almeida',
    motivo: 'Tentativa de furto de materiais do almoxarifado detectada em 10/01/2025',
    data: '2025-01-10',
    status: 'ativo',
    empresa: 'Serviços Gerais Premium',
  },
  {
    id: 'ln2',
    nome: 'Marcos Vinicius Rocha',
    motivo: 'Comportamento agressivo com equipe de segurança e recusa em acatar normas internas',
    data: '2025-02-05',
    status: 'ativo',
  },
  {
    id: 'ln3',
    nome: 'Transportes Rápidos Ltda',
    motivo: 'Entrega de materiais divergentes da nota fiscal em múltiplas ocasiões',
    data: '2024-12-20',
    status: 'ativo',
  },
  {
    id: 'ln4',
    nome: 'Fernanda Abreu',
    motivo: 'Acesso não autorizado a área restrita - registro em 15/02/2025',
    data: '2025-02-15',
    status: 'inativo',
    empresa: 'Distribuidora Central',
  },
];

export const ACHADOS_PERDIDOS_INICIAL: AchadosPerdidosItem[] = [
  {
    id: 'ap1',
    descricao: 'Carteira de couro marrom com documentos',
    localEncontrado: 'Estacionamento - Vaga 08',
    data: '2025-03-14',
    status: 'achado',
    cor: 'Marrom',
    observacoes: 'Contém RG e cartões bancários',
  },
  {
    id: 'ap2',
    descricao: 'Chaveiro com 3 chaves',
    localEncontrado: 'Recepção - Sofá da sala de espera',
    data: '2025-03-13',
    status: 'achado',
    cor: 'Prata',
    observacoes: 'Chaveiro com logo de empresa',
  },
  {
    id: 'ap3',
    descricao: 'Notebook Dell Latitude',
    localEncontrado: 'Sala de reuniões B',
    data: '2025-03-12',
    status: 'devolvido',
    cor: 'Preto',
    observacoes: 'Devolvido ao dono - Roberto Lima (TI)',
  },
  {
    id: 'ap4',
    descricao: 'Celular Samsung Galaxy S23',
    localEncontrado: 'Refeitório',
    data: '2025-03-11',
    status: 'perdido',
    cor: 'Preto',
    observacoes: 'Pertence a visitante não identificado',
  },
  {
    id: 'ap5',
    descricao: 'Óculos de sol Ray-Ban',
    localEncontrado: 'Área de carga/descarga',
    data: '2025-03-10',
    status: 'achado',
    cor: 'Preto/Dourado',
    observacoes: 'Armação em bom estado',
  },
];

// Generate fictional fluxo records
const today = '2025-03-15';
export const REGISTROS_FLUXO_INICIAIS: RegistroFluxo[] = [
  // Entregas 1
  {
    id: 'fl1',
    categoria: 'entregas1',
    data: today,
    horarioEntrada: '07:30',
    nome: 'José da Silva',
    empresa: 'Transportes Silva Ltda',
    rgCpf: '12.345.678-9',
    horarioSaida: '09:15',
  },
  {
    id: 'fl2',
    categoria: 'entregas1',
    data: today,
    horarioEntrada: '08:45',
    nome: 'Pedro Henrique Santos',
    empresa: 'Distribuidora Central',
    rgCpf: '23.456.789-0',
    horarioSaida: '',
  },
  {
    id: 'fl3',
    categoria: 'entregas1',
    data: today,
    horarioEntrada: '10:20',
    nome: 'Marcos Antônio Ferreira',
    empresa: 'Logística Rápida S.A.',
    rgCpf: '34.567.890-1',
    horarioSaida: '11:30',
  },
  {
    id: 'fl4',
    categoria: 'entregas1',
    data: '2025-03-14',
    horarioEntrada: '14:00',
    nome: 'André Luiz Costa',
    empresa: 'Serviços Gerais Premium',
    rgCpf: '45.678.901-2',
    horarioSaida: '15:45',
  },
  {
    id: 'fl5',
    categoria: 'entregas1',
    data: '2025-03-14',
    horarioEntrada: '16:30',
    nome: 'Ricardo Mendes',
    empresa: 'Transportes Silva Ltda',
    rgCpf: '56.789.012-3',
    horarioSaida: '',
  },
  {
    id: 'fl6',
    categoria: 'entregas1',
    data: '2025-03-13',
    horarioEntrada: '09:10',
    nome: 'Fernando Gomes',
    empresa: 'Distribuidora Central',
    rgCpf: '67.890.123-4',
    horarioSaida: '10:50',
  },
  // Visitantes
  {
    id: 'fl7',
    categoria: 'visitantes',
    nomeEmpresa: 'Dr. Paulo Renato / Advocacia Renato & Filhos',
    departamento: 'Diretoria',
    rgCpf: '987.654.321-00',
    data: today,
    horarioEntrada: '09:00',
    horarioSaida: '10:30',
  },
  {
    id: 'fl8',
    categoria: 'visitantes',
    nomeEmpresa: 'Luciana Moraes / Consultora Empresarial',
    departamento: 'RH',
    rgCpf: '876.543.210-11',
    data: today,
    horarioEntrada: '10:15',
    horarioSaida: '',
  },
  {
    id: 'fl9',
    categoria: 'visitantes',
    nomeEmpresa: 'Eng. Roberto Campos / Campos Engenharia',
    departamento: 'Logística',
    rgCpf: '765.432.109-22',
    data: today,
    horarioEntrada: '11:00',
    horarioSaida: '12:20',
  },
  {
    id: 'fl10',
    categoria: 'visitantes',
    nomeEmpresa: 'Carla Mendes / Auditora Externa',
    departamento: 'Financeiro',
    rgCpf: '654.321.098-33',
    data: '2025-03-14',
    horarioEntrada: '14:00',
    horarioSaida: '17:00',
  },
  {
    id: 'fl11',
    categoria: 'visitantes',
    nomeEmpresa: 'Thiago Almeida / Representante Comercial',
    departamento: 'Comercial',
    rgCpf: '543.210.987-44',
    data: '2025-03-14',
    horarioEntrada: '08:30',
    horarioSaida: '09:45',
  },
  {
    id: 'fl12',
    categoria: 'visitantes',
    nomeEmpresa: 'Sra. Elaine Pinto / Entrevista RH',
    departamento: 'RH',
    rgCpf: '432.109.876-55',
    data: '2025-03-13',
    horarioEntrada: '13:00',
    horarioSaida: '14:30',
  },
  // Prestadores
  {
    id: 'fl13',
    categoria: 'prestadores',
    nomeEmpresa: 'Eletricista João Batista / JB Elétrica',
    departamento: 'TI',
    rgCpf: '321.098.765-66',
    data: today,
    horarioEntrada: '07:00',
    horarioSaida: '11:30',
  },
  {
    id: 'fl14',
    categoria: 'prestadores',
    nomeEmpresa: 'Pedro Marcelino / Manutenção Total EIRELI',
    departamento: 'Almoxarifado',
    rgCpf: '210.987.654-77',
    data: today,
    horarioEntrada: '08:00',
    horarioSaida: '',
  },
  {
    id: 'fl15',
    categoria: 'prestadores',
    nomeEmpresa: 'Equipe de Limpeza / Serviços Gerais Premium',
    departamento: 'Recepção',
    rgCpf: '109.876.543-88',
    data: today,
    horarioEntrada: '06:00',
    horarioSaida: '14:00',
  },
  {
    id: 'fl16',
    categoria: 'prestadores',
    nomeEmpresa: 'Técnico Elevadores / Atlas Elevadores',
    departamento: 'Segurança',
    rgCpf: '098.765.432-99',
    data: '2025-03-14',
    horarioEntrada: '09:00',
    horarioSaida: '16:00',
  },
  {
    id: 'fl17',
    categoria: 'prestadores',
    nomeEmpresa: 'Marcos Pintor / Decora Pinturas',
    departamento: 'Diretoria',
    rgCpf: '987.654.321-01',
    data: '2025-03-13',
    horarioEntrada: '07:30',
    horarioSaida: '17:00',
  },
  // Pesagem
  {
    id: 'fl18',
    categoria: 'pesagem',
    data: today,
    empresa: 'Transportes Silva Ltda',
    placa: 'ABC-1D23',
    motorista: 'José da Silva',
    horarioEntrada: '06:30',
    pesoEntrada: 15200,
    horarioSaida: '08:45',
    pesoSaida: 8300,
  },
  {
    id: 'fl19',
    categoria: 'pesagem',
    data: today,
    empresa: 'Logística Rápida S.A.',
    placa: 'DEF-4E56',
    motorista: 'Antônio Carlos',
    horarioEntrada: '07:15',
    pesoEntrada: 22500,
    horarioSaida: '',
    pesoSaida: 0,
  },
  {
    id: 'fl20',
    categoria: 'pesagem',
    data: today,
    empresa: 'Distribuidora Central',
    placa: 'GHI-7F89',
    motorista: 'Roberto Nascimento',
    horarioEntrada: '09:30',
    pesoEntrada: 18800,
    horarioSaida: '11:00',
    pesoSaida: 5600,
  },
  {
    id: 'fl21',
    categoria: 'pesagem',
    data: '2025-03-14',
    empresa: 'Coleta Verde Ambiental',
    placa: 'JKL-0G12',
    motorista: 'Paulo Mendes',
    horarioEntrada: '10:00',
    pesoEntrada: 8500,
    horarioSaida: '12:30',
    pesoSaida: 12400,
  },
  {
    id: 'fl22',
    categoria: 'pesagem',
    data: '2025-03-14',
    empresa: 'Transportes Silva Ltda',
    placa: 'MNO-3H45',
    motorista: 'Fernando Gomes',
    horarioEntrada: '13:00',
    pesoEntrada: 19300,
    horarioSaida: '15:20',
    pesoSaida: 7200,
  },
  // Entregas 2
  {
    id: 'fl23',
    categoria: 'entregas2',
    data: today,
    horarioEntrada: '07:00',
    motorista: 'Claudinho Souza',
    cpfRg: '11.222.333-4',
    empresa: 'Transportes Silva Ltda',
    departamento: 'Almoxarifado',
    horarioSaida: '08:30',
  },
  {
    id: 'fl24',
    categoria: 'entregas2',
    data: today,
    horarioEntrada: '09:15',
    motorista: 'Valdir Santos',
    cpfRg: '22.333.444-5',
    empresa: 'Distribuidora Central',
    departamento: 'Logística',
    horarioSaida: '',
  },
  {
    id: 'fl25',
    categoria: 'entregas2',
    data: today,
    horarioEntrada: '11:45',
    motorista: 'Sebastião Lima',
    cpfRg: '33.444.555-6',
    empresa: 'Logística Rápida S.A.',
    departamento: 'Recepção',
    horarioSaida: '13:00',
  },
  {
    id: 'fl26',
    categoria: 'entregas2',
    data: '2025-03-14',
    horarioEntrada: '14:30',
    motorista: 'Orlando Pereira',
    cpfRg: '44.555.666-7',
    empresa: 'Serviços Gerais Premium',
    departamento: 'Almoxarifado',
    horarioSaida: '16:00',
  },
  {
    id: 'fl27',
    categoria: 'entregas2',
    data: '2025-03-13',
    horarioEntrada: '08:00',
    motorista: 'Nilson Ribeiro',
    cpfRg: '55.666.777-8',
    empresa: 'Transportes Silva Ltda',
    departamento: 'Logística',
    horarioSaida: '09:45',
  },
  // Coleta
  {
    id: 'fl28',
    categoria: 'coleta',
    rgCpf: '66.777.888-9',
    horarioEntrada: '06:00',
    placa: 'PQR-6I78',
    empresa: 'Coleta Verde Ambiental',
    motorista: 'Walter Nascimento',
    data: today,
    horarioSaida: '07:45',
  },
  {
    id: 'fl29',
    categoria: 'coleta',
    rgCpf: '77.888.999-0',
    horarioEntrada: '08:30',
    placa: 'STU-9J01',
    empresa: 'Coleta Verde Ambiental',
    motorista: 'Augusto Pinto',
    data: today,
    horarioSaida: '',
  },
  {
    id: 'fl30',
    categoria: 'coleta',
    rgCpf: '88.999.000-1',
    horarioEntrada: '10:00',
    placa: 'VWX-2K34',
    empresa: 'Recicla Mais Ltda',
    motorista: 'Dênis Barbosa',
    data: today,
    horarioSaida: '11:30',
  },
  {
    id: 'fl31',
    categoria: 'coleta',
    rgCpf: '99.000.111-2',
    horarioEntrada: '13:00',
    placa: 'YZA-5L67',
    empresa: 'Coleta Verde Ambiental',
    motorista: 'Mauro Tavares',
    data: '2025-03-14',
    horarioSaida: '14:45',
  },
  {
    id: 'fl32',
    categoria: 'coleta',
    rgCpf: '00.111.222-3',
    horarioEntrada: '15:30',
    placa: 'BCD-8M90',
    empresa: 'Eco Reciclagem',
    motorista: 'Hugo Ferreira',
    data: '2025-03-14',
    horarioSaida: '17:00',
  },
  // Movimentação Interna Colaboradores
  {
    id: 'fl33',
    categoria: 'movimentacao',
    nomeColaborador: 'Carlos Eduardo Silva',
    rgCpf: '12.345.678-9',
    horarioEntrada: '07:00',
    horarioSaida: '11:30',
    autorizadoPor: 'João Pedro Oliveira',
    assinaturaColaborador: '',
    porteiro: 'Carlos Eduardo Silva',
    data: today,
  },
  {
    id: 'fl34',
    categoria: 'movimentacao',
    nomeColaborador: 'Ana Maria Costa',
    rgCpf: '23.456.789-0',
    horarioEntrada: '08:15',
    horarioSaida: '',
    autorizadoPor: 'Maria Fernanda Santos',
    assinaturaColaborador: '',
    porteiro: 'Carlos Eduardo Silva',
    data: today,
  },
  {
    id: 'fl35',
    categoria: 'movimentacao',
    nomeColaborador: 'Roberto Junior Lima',
    rgCpf: '34.567.890-1',
    horarioEntrada: '09:00',
    horarioSaida: '12:00',
    autorizadoPor: 'Fernando Souza',
    assinaturaColaborador: '',
    porteiro: 'Carlos Eduardo Silva',
    data: '2025-03-14',
  },
  {
    id: 'fl36',
    categoria: 'movimentacao',
    nomeColaborador: 'Maria Fernanda Santos',
    rgCpf: '45.678.901-2',
    horarioEntrada: '13:30',
    horarioSaida: '',
    autorizadoPor: 'Pedro Oliveira',
    assinaturaColaborador: '',
    porteiro: 'Carlos Eduardo Silva',
    data: '2025-03-14',
  },
  // Correspondências
  {
    id: 'fl37',
    categoria: 'correspondencias',
    destinatario: 'Fernando Souza',
    remetente: 'Advocacia Renato & Filhos',
    tipo: 'Documento',
    departamento: 'Diretoria',
    horarioEntrada: '09:30',
    horarioSaida: '14:00',
    quemRetirou: 'Fernando Souza',
    porteiro: 'Carlos Eduardo Silva',
    data: today,
  },
  {
    id: 'fl38',
    categoria: 'correspondencias',
    destinatario: 'Maria Fernanda Santos',
    remetente: 'Sedex — Correios',
    tipo: 'Encomenda',
    departamento: 'RH',
    horarioEntrada: '10:15',
    horarioSaida: '',
    quemRetirou: '',
    porteiro: 'Carlos Eduardo Silva',
    data: today,
  },
  {
    id: 'fl39',
    categoria: 'correspondencias',
    destinatario: 'Roberto Junior Lima',
    remetente: 'Dell Computadores',
    tipo: 'Pacote',
    departamento: 'TI',
    horarioEntrada: '11:45',
    horarioSaida: '13:20',
    quemRetirou: 'Roberto Junior Lima',
    porteiro: 'Carlos Eduardo Silva',
    data: today,
  },
  {
    id: 'fl40',
    categoria: 'correspondencias',
    destinatario: 'Pedro Oliveira',
    remetente: 'Banco do Brasil',
    tipo: 'Carta',
    departamento: 'Financeiro',
    horarioEntrada: '14:00',
    horarioSaida: '',
    quemRetirou: '',
    porteiro: 'Carlos Eduardo Silva',
    data: '2025-03-14',
  },
];
// ── Veículos seed data ──
export const VEICULOS_INICIAIS: RegistroVeiculo[] = [
  {
    id: 'vei1',
    placa: 'ABC-1D23',
    modelo: 'Volvo FH',
    cor: 'Branco',
    tipo: 'Entregador',
    motoristaNome: 'José da Silva',
    motoristaDoc: '12.345.678-9',
    empresa: 'Transportes Silva Ltda',
    vaga: 'CD1',
    data: today,
    horarioEntrada: '06:30',
    horarioSaida: '08:45',
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'vei2',
    placa: 'DEF-4E56',
    modelo: 'Scania R450',
    cor: 'Prata',
    tipo: 'Entregador',
    motoristaNome: 'Antônio Carlos',
    motoristaDoc: '98.765.432-1',
    empresa: 'Logística Rápida S.A.',
    vaga: 'CD2',
    data: today,
    horarioEntrada: '07:15',
    horarioSaida: '',
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'vei3',
    placa: 'GHI-7F89',
    modelo: 'VW Delivery',
    cor: 'Branco',
    tipo: 'Prestador',
    motoristaNome: 'Roberto Nascimento',
    motoristaDoc: '34.567.890-1',
    empresa: 'Distribuidora Central',
    vaga: 'V1',
    data: today,
    horarioEntrada: '09:30',
    horarioSaida: '11:00',
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'vei4',
    placa: 'MNO-3H45',
    modelo: 'Hyundai HB20',
    cor: 'Preto',
    tipo: 'Visitante',
    motoristaNome: 'Dr. Paulo Renato',
    motoristaDoc: '987.654.321-00',
    empresa: 'Advocacia Renato & Filhos',
    vaga: 'V3',
    data: today,
    horarioEntrada: '09:00',
    horarioSaida: '10:30',
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'vei5',
    placa: 'PQR-6I78',
    modelo: 'Mercedes Atego',
    cor: 'Branco',
    tipo: 'Entregador',
    motoristaNome: 'Walter Nascimento',
    motoristaDoc: '66.777.888-9',
    empresa: 'Coleta Verde Ambiental',
    vaga: 'CD3',
    data: today,
    horarioEntrada: '06:00',
    horarioSaida: '07:45',
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'vei6',
    placa: 'STU-9J01',
    modelo: 'Fiat Strada',
    cor: 'Vermelho',
    tipo: 'Entregador',
    motoristaNome: 'Augusto Pinto',
    motoristaDoc: '77.888.999-0',
    empresa: 'Coleta Verde Ambiental',
    vaga: 'V5',
    data: today,
    horarioEntrada: '08:30',
    horarioSaida: '',
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'vei7',
    placa: 'XYZ-5L67',
    modelo: 'Toyota Corolla',
    cor: 'Prata',
    tipo: 'Colaborador',
    motoristaNome: 'Fernando Souza',
    motoristaDoc: '456.789.012-33',
    empresa: '',
    vaga: 'V8',
    data: '2025-03-14',
    horarioEntrada: '07:45',
    horarioSaida: '18:00',
    porteiro: 'Carlos Eduardo Silva',
  },
];
// ── Pré-Autorização seed data ──
export const PRE_AUTORIZACAO_INICIAL: PreAutorizacao[] = [
  {
    id: 'pa1',
    visitanteNome: 'Dra. Ana Luíza Ferreira',
    visitanteDoc: '123.456.789-00',
    visitanteEmpresa: 'Ferreira & Associados Advocacia',
    departamento: 'Diretoria',
    autorizadoPor: 'Fernando Souza',
    motivo: 'Reunião sobre contrato de prestação de serviços',
    dataPrevista: today,
    horarioPrevisto: '14:00',
    status: 'agendado',
  },
  {
    id: 'pa2',
    visitanteNome: 'Carlos Mota',
    visitanteDoc: '987.654.321-11',
    visitanteEmpresa: 'Mota Instalações Elétricas',
    departamento: 'TI',
    autorizadoPor: 'Roberto Junior Lima',
    motivo: 'Manutenção elétrica no data center',
    dataPrevista: today,
    horarioPrevisto: '08:00',
    status: 'confirmado',
    dataConfirmacao: today,
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'pa3',
    visitanteNome: 'Juliana Santos',
    visitanteDoc: '456.789.012-22',
    visitanteEmpresa: '',
    departamento: 'RH',
    autorizadoPor: 'Maria Fernanda Santos',
    motivo: 'Entrevista de emprego — vaga analista administrativo',
    dataPrevista: '2025-03-16',
    horarioPrevisto: '10:00',
    status: 'agendado',
  },
  {
    id: 'pa4',
    visitanteNome: 'Marcos Pintor',
    visitanteDoc: '321.654.987-33',
    visitanteEmpresa: 'Decora Pinturas',
    departamento: 'Diretoria',
    autorizadoPor: 'Fernando Souza',
    motivo: 'Pintura sala de reuniões',
    dataPrevista: '2025-03-13',
    horarioPrevisto: '07:30',
    status: 'expirado',
  },
  {
    id: 'pa5',
    visitanteNome: 'Pedro Almeida',
    visitanteDoc: '654.987.321-44',
    visitanteEmpresa: 'Almeida Consultoria',
    departamento: 'Financeiro',
    autorizadoPor: 'Pedro Oliveira',
    motivo: 'Auditoria trimestral',
    dataPrevista: today,
    horarioPrevisto: '09:00',
    status: 'cancelado',
  },
];

export const PROTOCOLOS_INICIAIS: ProtocoloEmergencia[] = [
  {
    id: 'pe1',
    tipo: 'incendio',
    titulo: 'Protocolo de Incêndio — Edifício Principal',
    descricao: 'Procedimento completo para combate a incêndio no edifício principal, incluindo evacuação, acionamento de alarmes e combate inicial.',
    etapas: [
      { id: 'pe1_e1', ordem: 1, descricao: 'Acionar alarme de incêndio e notificar o Corpo de Bombeiros (193)' },
      { id: 'pe1_e2', ordem: 2, descricao: 'Iniciar evacuação pelas rotas de fuga sinalizadas' },
      { id: 'pe1_e3', ordem: 3, descricao: 'Conferir todos os ambientes incluindo banheiros e áreas de serviço' },
      { id: 'pe1_e4', ordem: 4, descricao: 'Fechar portas e janelas ao sair para conter a propagação' },
      { id: 'pe1_e5', ordem: 5, descricao: 'Tentar combate inicial com extintores apenas se seguro' },
      { id: 'pe1_e6', ordem: 6, descricao: 'Dirigir-se ao ponto de encontro e fazer contagem de presentes' },
      { id: 'pe1_e7', ordem: 7, descricao: 'Aguardar instruções dos Bombeiros e não retornar ao local' },
    ],
    contatos: [
      { id: 'pe1_c1', nome: 'Corpo de Bombeiros', funcao: 'Emergência', telefone: '193', tipo: 'externo' },
      { id: 'pe1_c2', nome: 'Carlos Silva', funcao: 'Supervisor de Segurança', telefone: '(11) 99876-5432', tipo: 'interno' },
      { id: 'pe1_c3', nome: 'João Pedro Oliveira', funcao: 'Coordenador de Segurança', telefone: '(11) 98765-4321', tipo: 'interno' },
      { id: 'pe1_c4', nome: 'Defesa Civil', funcao: 'Apoio Emergencial', telefone: '199', tipo: 'externo' },
    ],
    observacoes: 'Nunca use elevadores durante incêndio. Extintores devem ser usados apenas por pessoas treinadas e se o fogo for pequeno.',
    ativo: true,
  },
  {
    id: 'pe2',
    tipo: 'evacuacao',
    titulo: 'Protocolo de Evacuação Geral',
    descricao: 'Procedimento de evacuação geral do edifício em situação de emergência, garantindo a saída segura de todos os ocupantes.',
    etapas: [
      { id: 'pe2_e1', ordem: 1, descricao: 'Acionar sirene de evacuação (3 toques longos)' },
      { id: 'pe2_e2', ordem: 2, descricao: 'Designar líderes de evacuação por andar/setor' },
      { id: 'pe2_e3', ordem: 3, descricao: 'Orientar saída pelas escadas de emergência — nunca usar elevadores' },
      { id: 'pe2_e4', ordem: 4, descricao: 'Assistir pessoas com mobilidade reduzida' },
      { id: 'pe2_e5', ordem: 5, descricao: 'Verificar banheiros, salas de reunião e áreas isoladas' },
      { id: 'pe2_e6', ordem: 6, descricao: 'Concentrar no ponto de encontro externo pré-definido' },
      { id: 'pe2_e7', ordem: 7, descricao: 'Fazer chamada e informar ausentes à equipe de resgate' },
    ],
    contatos: [
      { id: 'pe2_c1', nome: 'Carlos Silva', funcao: 'Líder de Evacuação', telefone: '(11) 99876-5432', tipo: 'interno' },
      { id: 'pe2_c2', nome: 'Ana Maria Costa', funcao: 'Apoio — Recepção', telefone: '(11) 99123-4567', tipo: 'interno' },
      { id: 'pe2_c3', nome: 'SAMU', funcao: 'Atendimento Médico', telefone: '192', tipo: 'externo' },
    ],
    observacoes: 'Ponto de encontro: estacionamento externo, setor B. Manter rotas de fuga sempre desobstruídas.',
    ativo: true,
  },
  {
    id: 'pe3',
    tipo: 'invasao',
    titulo: 'Protocolo de Invasão / Intrusão',
    descricao: 'Procedimento para situações de invasão ou tentativa de intrusão no edifício, protegendo ocupantes e acionando autoridades.',
    etapas: [
      { id: 'pe3_e1', ordem: 1, descricao: 'Acionar botão de pânico ou alarme silencioso' },
      { id: 'pe3_e2', ordem: 2, descricao: 'Trancar portas de acesso e permanecer em ambiente seguro' },
      { id: 'pe3_e3', ordem: 3, descricao: 'Ligar para a Polícia Militar (190) imediatamente' },
      { id: 'pe3_e4', ordem: 4, descricao: 'Não confrontar invasores — priorizar a segurança pessoal' },
      { id: 'pe3_e5', ordem: 5, descricao: 'Registrar características dos invasores se possível (sem se expor)' },
      { id: 'pe3_e6', ordem: 6, descricao: 'Aguardar chegada da polícia e seguir instruções' },
    ],
    contatos: [
      { id: 'pe3_c1', nome: 'Polícia Militar', funcao: 'Emergência', telefone: '190', tipo: 'externo' },
      { id: 'pe3_c2', nome: 'Carlos Silva', funcao: 'Supervisor de Segurança', telefone: '(11) 99876-5432', tipo: 'interno' },
      { id: 'pe3_c3', nome: 'Fernando Souza', funcao: 'Diretoria', telefone: '(11) 97654-3210', tipo: 'interno' },
    ],
    observacoes: 'Em caso de invasão armada, não ofereça resistência. Mantenha a calma e siga instruções dos invasores até a chegada da polícia.',
    ativo: true,
  },
  {
    id: 'pe4',
    tipo: 'corte_energia',
    titulo: 'Protocolo de Corte de Energia Elétrica',
    descricao: 'Procedimento para situações de interrupção repentina de energia elétrica, garantindo segurança e continuidade das operações essenciais.',
    etapas: [
      { id: 'pe4_e1', ordem: 1, descricao: 'Acender lanternas e verificar iluminação de emergência' },
      { id: 'pe4_e2', ordem: 2, descricao: 'Verificar se o corte é geral ou localizado' },
      { id: 'pe4_e3', ordem: 3, descricao: 'Acionar gerador de emergência (sala de máquinas)' },
      { id: 'pe4_e4', ordem: 4, descricao: 'Desligar equipamentos sensíveis para evitar danos na retorno' },
      { id: 'pe4_e5', ordem: 5, descricao: 'Contatar concessionária de energia para informação' },
      { id: 'pe4_e6', ordem: 6, descricao: 'Monitorar sistemas CFTV e alarmes (possuem no-break)' },
    ],
    contatos: [
      { id: 'pe4_c1', nome: 'Roberto Lima', funcao: 'Técnico TI / Manutenção', telefone: '(11) 99345-6789', tipo: 'interno' },
      { id: 'pe4_c2', nome: 'Enel Distribuição', funcao: 'Concessionária de Energia', telefone: '0800-7272-120', tipo: 'externo' },
    ],
    observacoes: 'O gerador de emergência abastece iluminação de escadas, CFTV e sistema de combate a incêndio por até 4 horas.',
    ativo: true,
  },
  {
    id: 'pe5',
    tipo: 'ameaca_bomba',
    titulo: 'Protocolo de Ameaça de Bomba',
    descricao: 'Procedimento para lidar com ameaças de artefato explosivo, incluindo evacuação e busca sistemática.',
    etapas: [
      { id: 'pe5_e1', ordem: 1, descricao: 'Manter a calma e registrar detalhes da ameaça (horário, meio, conteúdo)' },
      { id: 'pe5_e2', ordem: 2, descricao: 'Notificar Polícia Militar (190) e Polícia Civil (197)' },
      { id: 'pe5_e3', ordem: 3, descricao: 'Iniciar evacuação silenciosa — sem mencionar bomba aos ocupantes' },
      { id: 'pe5_e4', ordem: 4, descricao: 'Equipe treinada realiza varredura visual em áreas comuns' },
      { id: 'pe5_e5', ordem: 5, descricao: 'Não tocar em objetos suspeitos — isolar a área com distância mínima de 100m' },
      { id: 'pe5_e6', ordem: 6, descricao: 'Aguardar equipe de bomba da Polícia e seguir instruções' },
    ],
    contatos: [
      { id: 'pe5_c1', nome: 'Polícia Militar', funcao: 'Emergência', telefone: '190', tipo: 'externo' },
      { id: 'pe5_c2', nome: 'Polícia Civil', funcao: 'Ameaça de Bomba', telefone: '197', tipo: 'externo' },
      { id: 'pe5_c3', nome: 'João Pedro Oliveira', funcao: 'Coordenador de Segurança', telefone: '(11) 98765-4321', tipo: 'interno' },
    ],
    observacoes: 'NUNCA use rádio comunicador ou celulares próximos a objetos suspeitos. A evacuação deve ser feita de forma calma e ordenada.',
    ativo: false,
  },
];

export const ATIVACOES_INICIAIS: AtivacaoProtocolo[] = [
  {
    id: 'at1',
    protocoloId: 'pe1',
    data: '2025-02-10',
    horario: '14:35',
    acionadoPor: 'Carlos Eduardo Silva',
    observacao: 'Alarme de fumaça ativado no 3º andar — falso alarme causado por queima de alimento no refeitório',
  },
  {
    id: 'at2',
    protocoloId: 'pe4',
    data: '2025-03-05',
    horario: '22:10',
    acionadoPor: 'Roberto Lima',
    observacao: 'Corte geral de energia — gerador acionado em 3 minutos. Energia retornou após 45 minutos.',
  },
];

export const OCORRENCIAS_INICIAIS: Ocorrencia[] = [
  {
    id: 'oc1',
    titulo: 'Tentativa de invasão pela área de carga',
    tipo: 'invasao',
    gravidade: 'grave',
    status: 'em_andamento',
    data: today,
    horario: '02:30',
    local: 'Área de Carga/Descarga',
    descricao: 'Indivíduo não identificado tentou acessar a área interna pelo portão de carga. Foi percebido pelo sistema de CFTV e a polícia foi acionada.',
    envolvidos: 'Indivíduo não identificado — masculino, aproximadamente 30 anos, vestimenta escura',
    acaoTomada: 'Acionamento da polícia militar (190). Portão trancado e área isolada. Câmeras gravando.',
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'oc2',
    tipo: 'alarme',
    titulo: 'Disparo de alarme — Setor Almoxarifado',
    gravidade: 'moderada',
    status: 'resolvida',
    data: today,
    horario: '04:15',
    local: 'Almoxarifado',
    descricao: 'Alarme do setor do almoxarifado disparou sem causa aparente. Verificação in loco realizada.',
    envolvidos: 'Nenhum',
    acaoTomada: 'Verificação presencial — nada encontrado. Alarme classificado como falso. Reset realizado.',
    porteiro: 'Carlos Eduardo Silva',
    resolucao: 'Alarme falso — sensor com defeito. Aberto chamado para manutenção.',
  },
  {
    id: 'oc3',
    tipo: 'perturbacao',
    titulo: 'Perturbação por funcionário terceirizado',
    gravidade: 'leve',
    status: 'resolvida',
    data: '2025-03-14',
    horario: '16:45',
    local: 'Refeitório',
    descricao: 'Funcionário da equipe de limpeza fez barulho excessivo no refeitório durante o horário de trabalho, incomodando colaboradores.',
    envolvidos: 'Pedro Marcelino — Serviços Gerais Premium',
    acaoTomada: 'Funcionário orientado a manter silêncio. Empresa notificada.',
    porteiro: 'Carlos Eduardo Silva',
    resolucao: 'Funcionário orientado. Empresa prestadora notificada formalmente.',
  },
  {
    id: 'oc4',
    tipo: 'veiculo_suspeito',
    titulo: 'Veículo suspeito estacionado na frente',
    gravidade: 'moderada',
    status: 'encaminhada',
    data: '2025-03-14',
    horario: '22:00',
    local: 'Estacionamento Externo — Vaga E1',
    descricao: 'Veículo Fiat Uno prata, placa ABC-1234, estacionado há mais de 3 horas sem identificação. Motorista não localizado.',
    envolvidos: 'Veículo Fiat Uno prata — placa ABC-1234',
    acaoTomada: 'Registro da placa. Tentativa de contato com proprietário. Acionado supervisor de plantão.',
    porteiro: 'Carlos Eduardo Silva',
  },
  {
    id: 'oc5',
    tipo: 'vandalismo',
    titulo: 'Vandalismo no banheiro do térreo',
    gravidade: 'leve',
    status: 'aberta',
    data: '2025-03-13',
    horario: '11:20',
    local: 'Banheiro Térreo — Ala A',
    descricao: 'Pichação encontrada nas paredes do banheiro masculino do térreo. Não há identificação do autor.',
    envolvidos: 'Autor não identificado',
    acaoTomada: 'Registro fotográfico (futuro). Limpeza solicitada ao facilities.',
    porteiro: 'Carlos Eduardo Silva',
  },
];

// ── Rondas seed data ──
export const RONDAS_INICIAIS: Ronda[] = [
  {
    id: 'rn1',
    rota: 'Rota Principal — Portaria > Garagem > Área de Carga > Corredores',
    data: today,
    horarioInicio: '22:00',
    horarioFim: '22:35',
    status: 'concluida',
    porteiro: 'Carlos Eduardo Silva',
    pontos: [
      { id: 'pt1', rondaId: 'rn1', ponto: 'Portaria Principal', horarioPrevisto: '22:00', horarioReal: '22:00', status: 'ok', observacao: '' },
      { id: 'pt2', rondaId: 'rn1', ponto: 'Garagem Subsolo', horarioPrevisto: '22:10', horarioReal: '22:12', status: 'ok', observacao: '' },
      { id: 'pt3', rondaId: 'rn1', ponto: 'Área de Carga/Descarga', horarioPrevisto: '22:20', horarioReal: '22:22', status: 'irregularidade', observacao: 'Portão de carga semiaberto — fechado manualmente' },
      { id: 'pt4', rondaId: 'rn1', ponto: 'Corredor Ala A', horarioPrevisto: '22:25', horarioReal: '22:28', status: 'ok', observacao: '' },
      { id: 'pt5', rondaId: 'rn1', ponto: 'Corredor Ala B', horarioPrevisto: '22:30', horarioReal: '22:33', status: 'ok', observacao: '' },
      { id: 'pt6', rondaId: 'rn1', ponto: 'Recepção', horarioPrevisto: '22:35', horarioReal: '22:35', status: 'ok', observacao: '' },
    ],
  },
  {
    id: 'rn2',
    rota: 'Rota Externa — Perímetro > Estacionamento > Área Verde',
    data: today,
    horarioInicio: '01:00',
    horarioFim: '',
    status: 'em_andamento',
    porteiro: 'Carlos Eduardo Silva',
    pontos: [
      { id: 'pt7', rondaId: 'rn2', ponto: 'Portaria Principal', horarioPrevisto: '01:00', horarioReal: '01:00', status: 'ok', observacao: '' },
      { id: 'pt8', rondaId: 'rn2', ponto: 'Estacionamento Externo', horarioPrevisto: '01:10', horarioReal: '01:12', status: 'ok', observacao: '' },
      { id: 'pt9', rondaId: 'rn2', ponto: 'Perímetro Norte', horarioPrevisto: '01:20', horarioReal: '01:22', status: 'ok', observacao: '' },
      { id: 'pt10', rondaId: 'rn2', ponto: 'Perímetro Sul', horarioPrevisto: '01:30', horarioReal: '', status: 'ok', observacao: '' },
      { id: 'pt11', rondaId: 'rn2', ponto: 'Área Verde', horarioPrevisto: '01:40', horarioReal: '', status: 'ok', observacao: '' },
      { id: 'pt12', rondaId: 'rn2', ponto: 'Casa de Máquinas', horarioPrevisto: '01:45', horarioReal: '', status: 'ok', observacao: '' },
    ],
  },
  {
    id: 'rn3',
    rota: 'Rota Noturna — Portaria > Pisos > Escadas > Terraço',
    data: '2025-03-14',
    horarioInicio: '23:00',
    horarioFim: '23:40',
    status: 'concluida',
    porteiro: 'Carlos Eduardo Silva',
    pontos: [
      { id: 'pt13', rondaId: 'rn3', ponto: 'Portaria Principal', horarioPrevisto: '23:00', horarioReal: '23:00', status: 'ok', observacao: '' },
      { id: 'pt14', rondaId: 'rn3', ponto: 'Corredor Ala A', horarioPrevisto: '23:10', horarioReal: '23:11', status: 'ok', observacao: '' },
      { id: 'pt15', rondaId: 'rn3', ponto: 'Corredor Ala B', horarioPrevisto: '23:15', horarioReal: '23:17', status: 'ok', observacao: '' },
      { id: 'pt16', rondaId: 'rn3', ponto: 'Terraço', horarioPrevisto: '23:25', horarioReal: '23:28', status: 'irregularidade', observacao: 'Luz de emergência apagada no acesso ao terraço' },
      { id: 'pt17', rondaId: 'rn3', ponto: 'Recepção', horarioPrevisto: '23:35', horarioReal: '23:38', status: 'ok', observacao: '' },
      { id: 'pt18', rondaId: 'rn3', ponto: 'Portaria Principal', horarioPrevisto: '23:40', horarioReal: '23:40', status: 'ok', observacao: '' },
    ],
  },
];

// ── Checklist de Turno seed data ──
export const CHECKLISTS_INICIAIS: ChecklistTurno[] = [
  {
    id: 'ck1',
    data: today,
    horarioPassagem: '06:00',
    porteiroSaindo: 'Roberto Nascimento',
    porteiroEntrando: 'Carlos Eduardo Silva',
    itens: ITENS_CHECKLIST_PADRAO.map((item, idx) => ({
      id: `ck1_it${idx}`,
      checklistId: 'ck1',
      item,
      checked: idx !== 5, // 'Equipamentos de segurança conferidos' unchecked
      observacao: idx === 5 ? 'Rádio comunicador com bateria fraca — solicitar troca' : '',
    })),
    ocorrenciasRepassadas: 'Alarme falso no almoxarifado às 04:15. Sensor com defeito — chamado de manutenção aberto.',
    correspondenciasPendentes: '2 correspondências no RH não retiradas. 1 pacote no Financeiro.',
    chavesPendentes: 'Nenhuma',
    observacoesGerais: 'Turno noturno tranquilo. Veículo suspeito reportado ontem ainda sem retorno.',
    status: 'concluido',
  },
  {
    id: 'ck2',
    data: today,
    horarioPassagem: '14:00',
    porteiroSaindo: 'Carlos Eduardo Silva',
    porteiroEntrando: 'Ana Maria Costa',
    itens: ITENS_CHECKLIST_PADRAO.map((item, idx) => ({
      id: `ck2_it${idx}`,
      checklistId: 'ck2',
      item,
      checked: true,
      observacao: '',
    })),
    ocorrenciasRepassadas: 'Tentativa de invasão registrada às 02:30. Polícia acionada. Portão de carga trancado.',
    correspondenciasPendentes: '3 correspondências pendentes — RH (2), Financeiro (1)',
    chavesPendentes: 'Chave da sala de reuniões B retirada e não devolvida por Roberto Lima (TI)',
    observacoesGerais: '',
    status: 'pendente',
  },
];

export const INSPECOES_INICIAIS: InspecaoDiaria[] = [
  {
    id: 'inp1',
    data: today,
    turno: 'diurno',
    itens: [
      { id: 'inp1_it0', inspecaoId: 'inp1', item: 'Portão principal — abertura/fechamento', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it1', inspecaoId: 'inp1', item: 'Cancela de entrada — funcionamento', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it2', inspecaoId: 'inp1', item: 'Cancela de saída — funcionamento', status: 'nao_conforme', observacao: 'Cancela travando ao abrir', acaoCorretiva: 'Solicitar manutenção da cancela' },
      { id: 'inp1_it3', inspecaoId: 'inp1', item: 'Interfone — comunicação e áudio', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it4', inspecaoId: 'inp1', item: 'Sistema CFTV — câmeras e gravação', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it5', inspecaoId: 'inp1', item: 'Monitor de câmeras — imagem nítida', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it6', inspecaoId: 'inp1', item: 'Alarme perimetral — status e teste', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it7', inspecaoId: 'inp1', item: 'Alarme interno — status e teste', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it8', inspecaoId: 'inp1', item: 'Extintores — validade e lacre', status: 'nao_conforme', observacao: 'Extintor do corredor B vencido', acaoCorretiva: 'Solicitar troca do extintor — corredor B' },
      { id: 'inp1_it9', inspecaoId: 'inp1', item: 'Iluminação de emergência — teste', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it10', inspecaoId: 'inp1', item: 'Rádio comunicador — bateria e sinal', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it11', inspecaoId: 'inp1', item: 'Sirene de emergência — teste', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it12', inspecaoId: 'inp1', item: 'Sistema de combate a incêndio — manômetro', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it13', inspecaoId: 'inp1', item: 'Senhas e chaves de emergência — conferência', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it14', inspecaoId: 'inp1', item: 'No-break / UPS — status e bateria', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it15', inspecaoId: 'inp1', item: 'Gerador de energia — nível combustível', status: 'inoperante', observacao: 'Gerador não liga — bateria descarregada', acaoCorretiva: 'Chamar técnico para substituir bateria do gerador' },
      { id: 'inp1_it16', inspecaoId: 'inp1', item: 'Catracas / controle de acesso — funcionamento', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it17', inspecaoId: 'inp1', item: 'Iluminação externa — geral', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it18', inspecaoId: 'inp1', item: 'Iluminação interna — corredores e escadas', status: 'ok', observacao: '', acaoCorretiva: '' },
      { id: 'inp1_it19', inspecaoId: 'inp1', item: 'Sinalização de emergência — visibilidade', status: 'ok', observacao: '', acaoCorretiva: '' },
    ],
    observacoesGerais: 'Cancela de saída com problema e extintor vencido. Gerador inoperante.',
    porteiro: 'Carlos Eduardo Silva',
    supervisor: '',
    status: 'concluida',
  },
  {
    id: 'inp2',
    data: '2025-03-14',
    turno: 'noturno',
    itens: ITENS_INSPECAO_PADRAO.map((item, idx) => ({
      id: `inp2_it${idx}`,
      inspecaoId: 'inp2',
      item,
      status: 'ok' as const,
      observacao: '',
      acaoCorretiva: '',
    })),
    observacoesGerais: 'Todos os equipamentos funcionando normalmente no turno noturno.',
    porteiro: 'Carlos Eduardo Silva',
    supervisor: 'João Pedro Oliveira',
    dataAprovacao: '2025-03-14',
    status: 'aprovada',
  },
];
